<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <LangVersion>13</LangVersion>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <NoWarn>$(NoWarn);SKEXP0001;SKEXP0010</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.SemanticKernel" Version="1.26.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SchemaNode\SchemaNode.csproj" />
  </ItemGroup>

</Project>
