using SchemaNode.Components;
using SchemaNode.Context;
using SchemaNode.Enum;
using SchemaNode.Node;
using SchemaNode.Property;
using SchemaNode.Property.Common;
using SchemaNode.Schema;
using SchemaNode.Utility;
using System.Text.Json.Nodes;
using System.Text.Json.Serialization;
using System.Text.RegularExpressions;
using SchemaNode.Attribute;
using SchemaNode.Function;
using SchemaNode.Property.App;
using SchemaNode.Property.Constraint;
using SchemaNode.Property.Core;
using static SchemaNode.Utility.Constant;
using static SchemaNode.Utility.AppConstant;
// ReSharper disable UnusedAutoPropertyAccessor.Global
// ReSharper disable MemberCanBePrivate.Global

namespace SchemaNode.Runtime;

/// <summary>
/// The in-memory application field schema representation
/// </summary>
public sealed class AppFieldType
{
    #region Constructors

    internal AppFieldType(AppType app, AppFieldSchema schema)
    {
        Application = app;
        _appFieldSchema = schema;
    }

    #endregion
    
    #region Fields

    private readonly AppFieldSchema _appFieldSchema;
    private IProperty[]? _props;
    private NodeType[]? _refTypes;
    
    #endregion
    
    #region Properties

    /// <summary>
    /// The application node
    /// </summary>
    public AppType Application { get; }

    /// <summary>
    /// The application name
    /// </summary>
    public string App => Application.Name;
    
    /// <summary>
    /// The seqno
    /// </summary>
    public int Seqno => _appFieldSchema.Seqno;

    /// <summary>
    /// The field name.
    /// </summary>
    public string Name => _appFieldSchema.Name;

    /// <summary>
    /// The field type.
    /// </summary>
    public string Type => _appFieldSchema.Type;

    /// <summary>
    /// The field is using increase update, no full data push allowed
    /// </summary>
    public bool? IncrUpdate { get; private set; }

    /// <summary>
    /// The field is disabled
    /// </summary>
    public bool? Disable { get; private set; }
    
    /// <summary>
    /// The field is readonly
    /// </summary>
    public bool? Readonly { get; private set; }
    
    /// <summary>
    /// The field type node
    /// </summary>
    public ValueType? ValueType { get; private set; }
    
    /// <summary>
    /// The foreign key settings
    /// </summary>
    public Foreign[]? Foreigns { get; private set; }

    /// <summary>
    /// The field view settings
    /// </summary>
    public FieldView? View { get; private set; }

    /// <summary>
    /// Whether the field is a view for foreign view, only readable
    /// </summary>
    public bool IsForeignView => !string.IsNullOrWhiteSpace(View?.App);

    #endregion
    
    #region Push

    /// <summary>
    /// The field function node
    /// </summary>
    public FunctionType? PushFunc { get; private set; }

    /// <summary>
    /// The call arguments
    /// </summary>
    public AppFieldType? PushSource { get; private set; }
    
    /// <summary>
    /// The push function schema
    /// </summary>
    public FunctionTypeSchema? PushFuncSchema { get; private set; }
    
    /// <summary>
    /// The third-party push field info
    /// </summary>
    public DataPushThirdFieldInfo[]? ThirdPushFields { get; private set; }

    #endregion
    
    #region Obselete
    
    /// <summary>
    /// The push function
    /// </summary>
    [Obsolete]
    public string? Push => _appFieldSchema?.Push ?? string.Empty;

    /// <summary>
    /// The push source field
    /// </summary>
    [Obsolete]
    public string? Source => _appFieldSchema?.Source ?? string.Empty;

    /// <summary>
    /// The authentication policy, normally row policy
    /// </summary>
    [Obsolete]
    public PolicyItem[]? Auths { get; private set; }

    /// <summary>
    /// Row filter policy
    /// </summary>
    [Obsolete]
    public RowPolicy[]? RowAuths { get; private set; }

    /// <summary>
    /// The column access policy
    /// </summary>
    [Obsolete]
    public ColPolicy[]? ColAuths { get; private set; }

    /// <summary>
    /// The field storage topology, which defines how the field data is stored in the database.
    /// </summary>
    [Obsolete]
    public FieldStorageTopology? Topology { get; private set; }

    /// <summary>
    /// The given table name if specified, otherwise the table name will be generated by the system based on the app and field name
    /// </summary>
    [Obsolete]
    public string? TableName { get; private set; }
    
    /// <summary>
    /// The given attribute table name if specified, otherwise the attribute table name will be generated by the system based on the app and field name
    /// </summary>
    [Obsolete]
    public string? AttrTableName { get; private set; }
        
    /// <summary>
    /// Enable clear data
    /// </summary>
    [Obsolete]
    public bool? AllowClear { get; private set; }

    /// <summary>
    /// The combine rule for struct or struct-array type
    /// </summary>
    [Obsolete]
    public DataCombine[]? Combines { get; private set; }

    /// <summary>
    /// The field filters
    /// </summary>
    [Obsolete]
    public FieldFilter[]? Filters { get; private set; }

    #endregion

    #region States

    /// <summary>
    /// The application field error
    /// </summary>
    public string? Error { get; private set; }

    /// <summary>
    /// Enable dynamic table
    /// </summary>
    public bool EnableDynamicTable => Readonly != true && Disable != true;

    /// <summary>
    /// Has observers
    /// </summary>
    public bool HasObserver => _observers is { Count: > 0 };

    #endregion

    #region Relationship

    /// <summary>
    /// The fields that subscribe the update of this field.
    /// </summary>
    public IReadOnlyList<AppFieldType>? Observers => _observers;
    
    /// <summary>
    ///  the observers in the same app
    /// </summary>
    List<AppFieldType>? _observers;
    
    #endregion
    
    #region Dynamic table schema

    /// <summary>
    /// The dynamic table schema
    /// </summary>
    public DynamicTableSchema? Schema { get; internal set; }
    
    #endregion
    
    #region Method

    /// <summary>
    /// Load the app field schema
    /// </summary>
    public async Task LoadAsync(SchemaContext context)
    {
        Error = null;
        
        ValueType = await context.GetNodeTypeAsync<ValueType>(Type);
        if (ValueType == null) Error = AppErrorCodes.APP_FIELD_TYPE_NOT_VALID;
        
        _props = _appFieldSchema.GetProperties(context.Runtime.GetSchemaKindProperties(SCHEMA_KIND_APP_FIELD)).ToArray();
        (_refTypes, Error) = await _appFieldSchema.LoadPropertiesAsync(context, _props, ValueType);

        _appFieldSchema.Error = Error;

        IncrUpdate = GetProperty<IncrUpdate>()?.Value;
        Readonly = GetProperty<ReadOnly>()?.Value;
        Disable = GetProperty<Disable>()?.Value;

        Foreigns = _appFieldSchema.Foreigns;
        View = _appFieldSchema.View;

        // Loading source & push
        if (!string.IsNullOrWhiteSpace(_appFieldSchema.Source))
        {
            if (await context.GetNodeTypeAsync<FunctionType>(_appFieldSchema.Push ?? string.Empty) is { Args.Length: 1 } funcNode)
            {
                PushFunc = funcNode;
                
                AppFieldType? pushSource = Application.GetField(_appFieldSchema.Source);
                if (pushSource == null || (pushSource.ValueType ?? await context.GetNodeTypeAsync<ValueType>(pushSource.Type))
                    is not ArrayType { Element: not null, Primary: { Count: > 0}} array ||
                    funcNode.Args[0].ValueType != null && funcNode.Args[0].ValueType is not GenericType && 
                    !array.Element.IsAssignableTo(funcNode.Args[0].ValueType!))
                {
                    Error = AppErrorCodes.APP_FIELD_PUSH_FUNC_NOT_VALID;
                }
                else
                {
                    // Register to observers
                    pushSource.AddObserver(this);
                    PushSource = pushSource;
        
                    // Compile with data push compile context
                    funcNode.ClearRuntimeFuncCache<DataPushCompileContext>(); // must reset the field reference
                    DataPushCompileContext compileContext = new DataPushCompileContext(context, funcNode);
                    try
                    {
                        FunctionTypeSchema pushSchema = await compileContext.VisitFunctionType();
                        DataPushThirdFieldInfo[] pushField = compileContext.ThirdFields;
                        if (pushField.Length > 0)
                        {
                            ThirdPushFields = compileContext.ThirdFields;
                            foreach (DataPushThirdFieldInfo push in pushField)
                                Application.GetField(push.Field)?.AddObserver(this);
                        }
                        PushFuncSchema = pushSchema;
                    }
                    catch(FunctionVisitException fv)
                    {
                        Error = fv.Status;
                    }
                    catch(Exception ex)
                    {
                        context.LogError(ex,$"AppType.LoadAsync: push function compile error for app {Name} field {field.Name}");
                        Error = AppErrorCodes.APP_FIELD_PUSH_FUNC_NOT_VALID;
                    }
                }
            }
            else
            {
                Error ??= AppErrorCodes.APP_FIELD_PUSH_FUNC_NOT_VALID;
            }
        }
        
        // valid for foreign key
        if (Foreigns is { Length: > 0 })
        {
            foreach (Foreign foreign in Foreigns)
            {
                if (string.IsNullOrWhiteSpace(foreign.Field) ||
                    string.IsNullOrWhiteSpace(foreign.App) ||
                    await context.GetAppTypeAsync(foreign.App) is not AppType refApp ||
                    refApp.ScopeType == AppScopeType.SystemLevel ||
                    structType == null || 
                    structType.GetField(foreign.Field) == null)
                {
                    field.Error = SchemaNodeStatus.ApplicationFieldWrongRef;
                    break;
                }
                reloadApps ??= [];
                reloadApps.Add(refApp);
            }
        }
        
        return new AppFieldType
        {
            Name = entity.Name,
            Type = entity.Type,
            Seqno = entity.Seqno,
            Display = entity.Display,
            Topology = entity.Topology,
            TableName = entity.TableName,
            AttrTableName = entity.AttrTableName,
            AllowClear =  entity.AllowClear,
            Push = entity.Push,
            Source = entity.Source,
            Auths = entity.Auths,
            RowAuths = entity.RowAuths,
            ColAuths = entity.ColAuths,
            Foreigns = entity.Foreigns,
            View = entity.View,
            IncrUpdate = entity.IncrUpdate,
            Frontend = entity.Frontend,
            Disable = entity.Disable,
            Readonly = entity.Readonly,
            SystemMaintain =  entity.SystemMaintain,
            Combine = entity.Combine,
            Combines = entity.Combines,
            Filters = entity.Filters,
            Extensions = entity.Extensions,
        };
    }
    
    /// <summary>
    /// Gets the property with given type
    /// </summary>
    public T? GetProperty<T>() where T : class, IProperty => _props?.OfType<T>().FirstOrDefault();

    /// <summary>
    /// Gets the constraints
    /// </summary>
    public IEnumerable<T> GetProperties<T>() => _props?.OfType<T>() ?? [];
    
    /// <summary>
    /// Gets the property by property name
    /// </summary>
    public IProperty? GetProperty(string propertyName) => _props?.FirstOrDefault(p => p.Name.Equals(propertyName, StringComparison.OrdinalIgnoreCase));

    /// <summary>
    /// Add observer
    /// </summary>
    public void AddObserver(AppFieldType observer)
    {
        _observers ??= [];
        if (!_observers.Contains(observer))
            _observers.Add(observer);
    }
    
    /// <summary>
    /// Gets the authentication policies with the scope
    /// </summary>
    public IEnumerable<PolicyItem> GetAuthPolicies(PolicyScope scope)
    {
        // Application policy first
        foreach (var i in Application.GetAuthPolicies(scope)) yield return i;

        // self policies
        if (Auths == null) yield break;
        foreach (var i in Auths.Where(p => p.Scope == scope))
            yield return i;
    }

    /// <summary>
    /// Gets the field authentication policies with the scope
    /// </summary>
    public IEnumerable<string> GetColPolicies(string fieldName)
    {
        ColPolicy? item = ColAuths?.FirstOrDefault(i => i.Name.Equals(fieldName, StringComparison.OrdinalIgnoreCase));
        if (item == null || item.Evaluators.Length == 0) yield break;
        foreach (var evaluator in item.Evaluators)
            yield return evaluator;
    }
    
    #endregion

    #region Dynamic table

    // Gets the data field dynamic table name
    public string DynamicTableName => 
        IsForeignView 
        ? View!.AppType?.GetField(View.Field)?.DynamicTableName ?? throw new Exception($"Foreign view app {View.App} or field {View.Field} not exist")
        : !string.IsNullOrWhiteSpace(TableName)
            ? TableName 
            : $"{DYNAMIC_TABLE_PREFIX}_{Regex.Replace(App, @"\W+", "_")}_{Name}";
    
    /// <summary>
    /// Gets the attribute table name for the field, which is used to store the attribute data of the field, only for dynamic type
    /// </summary>
    public string AttributeTableName => 
        IsForeignView
        ? View!.AppType?.GetField(View.Field)?.AttributeTableName ?? throw new Exception($"Foreign view app {View.App} or field {View.Field} not exist")
        : Topology == FieldStorageTopology.AttributeBased
            ? (!string.IsNullOrWhiteSpace(AttrTableName) 
                ? AttrTableName 
                : !string.IsNullOrWhiteSpace(TableName) 
                    ? $"{EAV_TABLE_PREFIX}_{TableName}" 
                    : $"{EAV_TABLE_PREFIX}_{Regex.Replace(App, @"\W+", "_")}_{Name}")
            : string.Empty;

    // Generate the dynamic table schema
    public DynamicTableSchema GenDynamicTableSchema()
    {
        // Generate the fields
        AnySchemaType node = ValueType!;
        List<DynamicTableField> fields = [];
        List<DynamicTableJoin>? joins = null;
        DataIndex[]? indexes = null;
        bool single = true;

        if (Frontend ?? false)
        {
            return new DynamicTableSchema
            {
                SchemaType = node,
                Single = true,
                Fields = fields,
            };
        }

        // The target app type, cover the field view
        bool isView = IsForeignView;
        AppType targetApp = !isView ? Application: (View?.AppType ?? throw new Exception($"Foreign view app {View?.App} not exist"));

        // context item isolation scope
        foreach ((string item, AnySchemaType type, bool isTarget) in targetApp.GetScopeContextItems())
        {
            DataTypeInfo info = GetDataTypeInfo(type, null, type is ScalarType { IsString: true } ? ENTITY_PRIMARY_KEY_MAX_LEN : null);

            // Add scope-target field
            fields.Add(new DynamicTableField
            {
                Name = item,
                Type = info.Type,
                MaxLength = info.MaxLength,
                SchemaType = type,
                Scope = true,
                Target = isTarget
            });
        }

        // value fields
        switch (node.Type)
        {
            case SchemaNode.Enum.SchemaType.Scalar:
            case SchemaNode.Enum.SchemaType.Enum:
            case SchemaNode.Enum.SchemaType.Json:
            {
                DataTypeInfo info = GetDataTypeInfo(node);
                fields.Add(new DynamicTableField
                {
                    Name = DYNAMIC_TABLE_VALUE_FIELD,
                    Type = info.Type,
                    MaxLength = info.MaxLength,
                    SchemaType = node
                });
                break;
            }
            case SchemaNode.Enum.SchemaType.Struct:
            {
                StructType structNode = (StructType)node;
                foreach (var sField in structNode.Fields)
                {
                    // Check if join the other field for display only
                    if (sField.DisplayOnly ?? false)
                    {
                        StructRelationSchema? relation = structNode.Relations?.FirstOrDefault(r =>
                            r.Field.Equals(sField.Name, StringComparison.OrdinalIgnoreCase) &&
                            r.Prop.Equals(PROPERTY_DEFAULT, StringComparison.OrdinalIgnoreCase) && 
                            DynamicTableSchema.IsReferenceFunc(r.Func));
                        if (relation == null) continue;

                        // app
                        string? app = relation.Args.FirstOrDefault()?.Value?.ToValue<string>();
                        if (string.IsNullOrWhiteSpace(app) || !targetApp.Name.Equals(app, StringComparison.OrdinalIgnoreCase)) continue; // the same app

                        // app field
                        string? field = relation.Args.ElementAtOrDefault(1)?.Value?.ToValue<string>();
                        if (string.IsNullOrWhiteSpace(field)) continue; // no app field
                        AppFieldType? appField = targetApp.GetField(field);
                        if (appField == null) continue; // app field not exist

                        // primary & struct
                        string[] primary = (appField.ValueType as ArrayType)?.Primary ?? [];
                        StructType? structType = (appField.ValueType is ArrayType arr ? arr.ElementSchemaType : appField.ValueType) as StructType;
                        if (structType == null || structType.Fields.Length == 0) continue;
                        if (primary.Length + 3 != relation.Args.Length) continue; // primary fields not contains

                        // data field
                        string? dataField = relation.Args.ElementAtOrDefault(2)?.Value?.ToValue<string>();
                        if (string.IsNullOrWhiteSpace(dataField) || dataField.Equals(Name, StringComparison.OrdinalIgnoreCase)) continue; // no data field
                        StructFieldSchema? dataFieldType = structType.GetField(dataField);
                        if (dataFieldType == null) continue; // data field not exist

                        // Check joins
                        if (joins == null || joins.All(j => !j.Field.Equals(field, StringComparison.OrdinalIgnoreCase)))
                        {
                            // collect keys
                            Dictionary<string, AppSchemaDataFilter> keyMap = new();

                            // build primary key
                            for (int i = 3; i < relation.Args.Length - 1; i++)
                            {
                                keyMap[primary[i - 3]] = !string.IsNullOrEmpty(relation.Args[i].Name)
                                    ? new AppSchemaDataFilterField(relation.Args[i].Name!)
                                    : new AppSchemaDataFilterValue(relation.Args[i].Value?.ToValue<string>() ?? string.Empty);
                            }

                            joins ??= [];
                            joins.Add(new DynamicTableJoin { Field = field, Matches = keyMap });
                        }

                        if (dataFieldType.SchemaType is StructType @struct)
                        {
                            // As complex fields
                            foreach (var ifield in @struct.Fields.Where(p => !(p.DisplayOnly ?? false)))
                            {
                                DataTypeInfo info = GetDataTypeInfo(ifield.SchemaType!, ifield);
                                fields.Add(new DynamicTableField
                                {
                                    Name = $"{sField.Name}{COMPLEX_SEP}{ifield.Name}",
                                    Complex = new DataFieldComplexInfo
                                    {
                                        Main = sField.Name,
                                        Field = ifield.Name
                                    },
                                    Type = info.Type,
                                    MaxLength = info.MaxLength,
                                    SchemaType = ifield.SchemaType!,
                                    JoinAppField = field,
                                    JoinDataField = $"{dataField}{COMPLEX_SEP}{ifield.Name}"
                                });
                            }
                        }
                        else
                        {
                            // As normal field
                            DataTypeInfo info = GetDataTypeInfo(dataFieldType.SchemaType!, dataFieldType);
                            fields.Add(new DynamicTableField
                            {
                                Name = sField.Name,
                                Type = info.Type,
                                MaxLength = info.MaxLength,
                                SchemaType = dataFieldType.SchemaType!,
                                JoinAppField = field,
                                JoinDataField = dataField
                            });
                        }
                    }

                    else if (sField.SchemaType?.Type == SchemaNode.Enum.SchemaType.Struct) // Check if the sfield use a struct type
                    {
                        // As complex fields
                        StructType subStructNode = (StructType)sField.SchemaType;
                        foreach (var iField in subStructNode.Fields.Where(p => !(p.DisplayOnly ?? false)))
                        {
                            DataTypeInfo info = GetDataTypeInfo(iField.SchemaType!, iField);
                            fields.Add(new DynamicTableField
                            {
                                Name = $"{sField.Name}{COMPLEX_SEP}{iField.Name}",
                                Complex = new DataFieldComplexInfo
                                {
                                    Main = sField.Name,
                                    Field = iField.Name
                                },
                                Type = info.Type,
                                MaxLength = info.MaxLength,
                                SchemaType = iField.SchemaType!
                            });
                        }
                    }
                    else
                    {
                        DataTypeInfo info = GetDataTypeInfo(sField.SchemaType!, sField);
                        fields.Add(new DynamicTableField
                        {
                            Name = sField.Name,
                            Type = info.Type,
                            MaxLength = info.MaxLength,
                            SchemaType = sField.SchemaType!
                        });
                    }
                }
                break;
            }
            case SchemaNode.Enum.SchemaType.Array:
            {
                ArrayType arrayNode = (ArrayType)node;
                node = arrayNode.ElementSchemaType!; // Record the base node for array
                indexes = arrayNode.Indexes;
                if (node is StructType structNode && arrayNode.Primary is { Length: > 0 })
                {
                    single = false;
                    var enableAttrTable = Topology == FieldStorageTopology.AttributeBased;

                    // Add primary fields
                    foreach (string n in arrayNode.Primary)
                    {
                        var sField = structNode.Fields.First(p => p.Name == n);
                        DataTypeInfo info = GetDataTypeInfo(sField.SchemaType!, sField);
                        fields.Add(new DynamicTableField
                        {
                            Name = sField.Name,
                            Type = info.Type,
                            Primary = true,
                            MaxLength = info.MaxLength,
                            SchemaType = sField.SchemaType!
                        });
                    }
                    
                    // Add normal fields
                    foreach (var sField in structNode.Fields.Where(p => !arrayNode.Primary.Contains(p.Name)))
                    {
                        // Check if join the other field for display only
                        if (sField.DisplayOnly ?? false)
                        {
                            StructRelationSchema? relation = structNode.Relations?.FirstOrDefault(r => 
                                r.Field.Equals(sField.Name, StringComparison.OrdinalIgnoreCase) && 
                                r.Prop.Equals(PROPERTY_DEFAULT, StringComparison.OrdinalIgnoreCase) && 
                                DynamicTableSchema.IsReferenceFunc(r.Func));
                            if (relation == null) continue;

                            // app
                            string? app = relation.Args.FirstOrDefault()?.Value?.ToValue<string>();
                            if (string.IsNullOrWhiteSpace(app) || !App.Equals(app, StringComparison.OrdinalIgnoreCase)) continue; // the same app

                            // app field
                            string? field = relation.Args.ElementAtOrDefault(1)?.Value?.ToValue<string>();
                            if (string.IsNullOrWhiteSpace(field)) continue; // no app field
                            AppFieldType? appField = Application.GetField(field);
                            if (appField == null) continue; // app field not exist

                            // primary & struct
                            string[] primary = (appField.ValueType as ArrayType)?.Primary ?? [];
                            StructType? structType = (appField.ValueType is ArrayType arr ? arr.ElementSchemaType : appField.ValueType) as StructType;
                            if (structType == null || structType.Fields.Length == 0) continue;
                            if (primary.Length + 3 != relation.Args.Length) continue; // primary fields not contains

                            // data field
                            string? dataField = relation.Args.ElementAtOrDefault(2)?.Value?.ToValue<string>();
                            if (string.IsNullOrWhiteSpace(dataField) || dataField.Equals(Name, StringComparison.OrdinalIgnoreCase)) continue; // no data field
                            StructFieldSchema? dataFieldType = structType.GetField(dataField);
                            if (dataFieldType == null) continue; // data field not exist

                            // Check joins
                            if (joins == null || joins.All(j => !j.Field.Equals(field, StringComparison.OrdinalIgnoreCase)))
                            {
                                // collect keys
                                Dictionary<string, AppSchemaDataFilter> keyMap = new();

                                // build primary key
                                for (int i = 3; i < relation.Args.Length - 1; i++)
                                {
                                    keyMap[primary[i - 3]] = !string.IsNullOrEmpty(relation.Args[i].Name)
                                        ? new AppSchemaDataFilterField(relation.Args[i].Name!)
                                        : new AppSchemaDataFilterValue(relation.Args[i].Value?.ToValue<string>() ?? string.Empty);
                                }

                                joins ??= [];
                                joins.Add(new DynamicTableJoin { Field = field, Matches = keyMap });
                            }

                            if (dataFieldType.SchemaType is StructType @struct)
                            {
                                // As complex fields
                                foreach (var ifield in @struct.Fields.Where(p => !(p.DisplayOnly ?? false)))
                                {
                                    DataTypeInfo info = GetDataTypeInfo(ifield.SchemaType!, ifield);
                                    fields.Add(new DynamicTableField
                                    {
                                        Name = $"{sField.Name}{COMPLEX_SEP}{ifield.Name}",
                                        Complex = new DataFieldComplexInfo
                                        {
                                            Main = sField.Name,
                                            Field = ifield.Name
                                        },
                                        Type = info.Type,
                                        MaxLength = info.MaxLength,
                                        SchemaType = ifield.SchemaType!,
                                        JoinAppField = field,
                                        JoinDataField = $"{dataField}{COMPLEX_SEP}{ifield.Name}"
                                    });
                                }
                            }
                            else
                            {
                                // As normal field
                                DataTypeInfo info = GetDataTypeInfo(dataFieldType.SchemaType!, dataFieldType);
                                fields.Add(new DynamicTableField
                                {
                                    Name = sField.Name,
                                    Type = info.Type,
                                    MaxLength = info.MaxLength,
                                    SchemaType = dataFieldType.SchemaType!,
                                    JoinAppField = field,
                                    JoinDataField = dataField
                                });
                            }
                        }

                        // Check if the s-field use a struct type
                        else  if (sField.SchemaType!.Type == SchemaNode.Enum.SchemaType.Struct)
                        {
                            // As complex fields
                            foreach (var ifield in ((StructType)sField.SchemaType).Fields.Where(p => !(p.DisplayOnly ?? false)))
                            {
                                DataTypeInfo info = GetDataTypeInfo(ifield.SchemaType!, ifield);
                                fields.Add(new DynamicTableField
                                {
                                    Name = $"{sField.Name}{COMPLEX_SEP}{ifield.Name}",
                                    Complex = new DataFieldComplexInfo
                                    {
                                        Main = sField.Name,
                                        Field = ifield.Name
                                    },
                                    Type = info.Type,
                                    MaxLength = info.MaxLength,
                                    SchemaType = ifield.SchemaType!
                                });
                            }
                        }
                        // Check if the field is a dynamic JSON field with attribute-based topology, which need to be stored in separated attribute table
                        else if (sField.SchemaType is JsonType && enableAttrTable)
                        {
                            AppRelationSchema? typeRelation = Application.Relations?.FirstOrDefault(r =>
                                r.Prop.Equals(PROPERTY_TYPE, StringComparison.OrdinalIgnoreCase) &&
                                r.FieldNode == this && sField.Name.Equals(r.DataField, StringComparison.OrdinalIgnoreCase));
                            StructRelationSchema? fieldRelation = structNode.Relations?.FirstOrDefault(r => 
                                r.Prop.Equals(PROPERTY_TYPE, StringComparison.OrdinalIgnoreCase) &&
                                r.Field.Equals(sField.Name, StringComparison.OrdinalIgnoreCase));

                            DataTypeInfo info = GetDataTypeInfo(sField.SchemaType, sField);
                            fields.Add(new DynamicTableField
                            {
                                Name = sField.Name,
                                Type = info.Type,
                                MaxLength = info.MaxLength,
                                SchemaType = sField.SchemaType!,
                                RelationType = typeRelation,
                                StructRelation = fieldRelation
                            });
                        }
                        else
                        {
                            DataTypeInfo info = GetDataTypeInfo(sField.SchemaType, sField);
                            fields.Add(new DynamicTableField
                            {
                                Name = sField.Name,
                                Type = info.Type,
                                MaxLength = info.MaxLength,
                                SchemaType = sField.SchemaType!
                            });
                        }
                    }
                }
                else
                {
                    fields.Add(new DynamicTableField
                    {
                        Name = DYNAMIC_TABLE_VALUE_FIELD,
                        Type = DynamicTableFieldType.Json,
                        SchemaType = node
                    });
                }
                break;
            }
            default:
                throw new ArgumentOutOfRangeException();
        }

        // Add the foreign key field if not added for query
        if (isView)
        {
            AppFieldType sourceField = View?.AppType?.GetField(View?.Field ?? "") ?? throw new Exception($"Invalid view source field: {View?.App}.{View?.Field}");
            Foreign foreign = sourceField.Foreigns?.FirstOrDefault(f => f.App.Equals(App, StringComparison.OrdinalIgnoreCase)) ?? throw new Exception($"Invalid view source field: {View?.App}.{View?.Field}");
            if (!fields.Any(f => f.Name.Equals(foreign.Field, StringComparison.OrdinalIgnoreCase)))
            {
                StructType eleType = (sourceField.ValueType is ArrayType arr ? arr.ElementSchemaType : sourceField.ValueType) as StructType ?? throw new Exception($"The {Name} field can't be used as view");
                StructFieldSchema fieldInfo = eleType.GetField(foreign.Field) ?? throw new Exception($"Invalid view source field: {View?.App}.{View?.Field}");
                DataTypeInfo info = GetDataTypeInfo(fieldInfo.SchemaType!, fieldInfo);
                fields.Add(new DynamicTableField
                {
                    Name = fieldInfo.Name,
                    Type = info.Type,
                    MaxLength = info.MaxLength,
                    SchemaType = fieldInfo.SchemaType!
                });
            }
        }

        return new DynamicTableSchema
        {
            AppFieldType = this,
            SchemaType = node,
            Single = single,
            Fields = fields,
            Indexes = indexes,
            IncrUpdate = IncrUpdate ?? false,
            Joins = joins?.ToArray()
        };
    }

    // Get scalar type mapping info
    static DataTypeInfo GetDataTypeInfo(AnySchemaType node, StructFieldSchema? field = null, decimal? upLimit = null, decimal? lowLimit = null)
    {
        if (node is ScalarType scalar)
        {
            // Get base scalar data type info
            DataTypeInfo info = JsonDataType;
            if (scalar.IsNumber)
            {
                upLimit ??= field?.GetUplimit<decimal>() ?? scalar.GetUplimit<decimal>();
                lowLimit ??= field?.GetLowlimit<decimal>() ?? scalar.GetLowlimit<decimal>();

                // Check Number value
                if (scalar.IsInt)
                {
                    // No Limit
                    if (!upLimit.HasValue || !lowLimit.HasValue)
                    {
                        info = new DataTypeInfo
                        {
                            Type = DynamicTableFieldType.BigInt
                        };
                    }
                    // Check Range
                    else if (lowLimit >= 0)
                    {
                        // Unsigned
                        decimal maxVal = upLimit.Value;
                        info = new DataTypeInfo
                        {
                            Type = maxVal switch
                            {
                                <= 0xffff => DynamicTableFieldType.USmallint,
                                <= 0xffffff => DynamicTableFieldType.UMediumint,
                                <= 0xffffffff => DynamicTableFieldType.UInt,
                                _ => DynamicTableFieldType.UBigInt
                            }
                        };
                    }
                    else
                    {
                        // Signed
                        decimal maxVal = Math.Max(Math.Abs(lowLimit.Value), Math.Abs(upLimit.Value));
                        info = new DataTypeInfo
                        {
                            Type = maxVal switch
                            {
                                <= 0x7fff => DynamicTableFieldType.Smallint,
                                <= 0x7fffff => DynamicTableFieldType.Mediumint,
                                <= 0x7fffffff => DynamicTableFieldType.Int,
                                _ => DynamicTableFieldType.BigInt
                            }
                        };
                    }
                }
                else if (scalar.IsSingle)
                {
                    info = new DataTypeInfo
                    {
                        Type = DynamicTableFieldType.Float
                    };
                }
                else
                {
                    info = new DataTypeInfo
                    {
                        Type = DynamicTableFieldType.Double
                    };
                }
            }
            else if (scalar.IsBool)
            {
                info = new DataTypeInfo
                {
                    Type = DynamicTableFieldType.Bool
                };
            }
            else if (scalar.IsChar)
            {
                info = new DataTypeInfo
                {
                    Type = DynamicTableFieldType.Char,
                    MaxLength = null
                };
            }
            else if (scalar.IsString)
            {
                upLimit ??= field?.GetUplimit<decimal>() ?? scalar.GetUplimit<decimal>();
                info = new DataTypeInfo
                {
                    Type = upLimit.HasValue ? upLimit.Value switch
                    {
                        <= 0xffff => DynamicTableFieldType.VarChar,
                        <= 0xffffff => DynamicTableFieldType.MediumText,
                        _ => DynamicTableFieldType.LongText
                    } : DynamicTableFieldType.LongText,
                    MaxLength = upLimit < 0xffff ? (int)upLimit.Value : null
                };
            }
            else if (scalar.IsDate)
            {
                info = new DataTypeInfo
                {
                    Type = DynamicTableFieldType.DateTime
                };
            }
            return info;
        }
        else if (node is EnumType @enum)
        {
            return new DataTypeInfo
            {
                Type = @enum.ValueType switch
                {
                    EnumValueType.String => DynamicTableFieldType.VarChar,
                    EnumValueType.Int => DynamicTableFieldType.BigInt,
                    EnumValueType.Flags => DynamicTableFieldType.UInt,
                    _ => throw new ArgumentOutOfRangeException()
                },
                MaxLength = @enum.ValueType == EnumValueType.String ? ENTITY_PRIMARY_KEY_MAX_LEN : null
            };
        }

        // Use Json for all others
        return JsonDataType;
    }

    static readonly DataTypeInfo JsonDataType = new()
    {
        Type = DynamicTableFieldType.Json
    };

    /// <summary>
    /// Validate field by DynamicTableSchema and return nullable
    /// </summary>
    public async Task<(bool isEmpty, AnySchemaNode? result, JsonNode? error)> ValidateDataAsync(SchemaContext context, JsonNode? token)
    {
        if (token.IsEmpty()) return (true, null, null);
        (AnySchemaNode? value, JsonNode? error) = await ValueType!.ValidateValueAsync(context, token!);
        return (false, value, error);
    }

    #endregion
}

#region Dynamic Data Helpers

/// <summary>
/// The field data change info
/// </summary>
internal record FieldDataChangeData(TransactionChangeOperation Operation, DataNode? Value, DataNode? Origin);

// The transaction change data
internal class TransactionChangeData
{
    /// <summary>
    /// The change operations
    /// </summary>
    public Dictionary<AppFieldType, List<FieldDataChangeData>> Changes { get; } = new();
}

/// <summary>
/// The push levels
/// </summary>
internal class FieldDataPushLevel
{
    /// <summary>
    /// The fields to be updated
    /// </summary>
    public List<AppFieldType> Fields { get; } = new();

    /// <summary>
    /// The next level to be updated
    /// </summary>
    public FieldDataPushLevel? Next { get; set; }
}

/// <summary>
/// The push argument
/// </summary>
internal struct FieldDataPushArg
{
    /// <summary>
    /// The value
    /// </summary>
    public DataNode? Value { get; set; }

    /// <summary>
    /// The origin value
    /// </summary>
    public DataNode? Origin { get; set; }

    /// <summary>
    /// Whether is array data
    /// </summary>
    public bool IsArray => Type is ArrayType;

    /// <summary>
    /// The value type
    /// </summary>
    public ValueType Type { get; set; }

    /// <summary>
    /// Whether is full data
    /// </summary>
    public bool IsFull { get; set; }

    /// <summary>
    /// Whether the data is changed
    /// </summary>
    public bool Changed { get; set; }
}

/// <summary>
/// The data type map info
/// </summary>
class DataTypeInfo
{
    /// <summary>
    /// The dynamic field type
    /// </summary>
    public DynamicTableFieldType Type { get; init; }

    /// <summary>
    /// The max length of the string type
    /// </summary>
    public int? MaxLength { get; init; }
}
#endregion