using System.Runtime.InteropServices;
using SchemaNode.Context;
using SchemaNode.Enum;
using SchemaNode.Schema;
using SchemaNode.Utility;
using System.Text.Json;
using System.Text.Json.Nodes;
using System.Text.RegularExpressions;
using SchemaNode.Components;
using SchemaNode.Node;
using static SchemaNode.Utility.Constant;
// ReSharper disable UnusedAutoPropertyAccessor.Global
// ReSharper disable MemberCanBePrivate.Global

namespace SchemaNode.Runtime;

/// <summary>
/// The in-memory application field schema representation
/// </summary>
public class AppFieldType
{
    #region Properties

    /// <summary>
    /// The application name
    /// </summary>
    public string App { get; internal set; } = string.Empty;
    
    /// <summary>
    /// The seqno
    /// </summary>
    public int Seqno { get; private init; }

    /// <summary>
    /// The field name.
    /// </summary>
    public required string Name { get; init; }

    /// <summary>
    /// The field type.
    /// </summary>
    public string Type { get; init; } = null!;

    /// <summary>
    /// The field chinese name.
    /// </summary>
    public LocaleString? Display { get; init; }

    /// <summary>
    /// The description of the field.
    /// </summary>
    public LocaleString? Desc { get; private init; }

    /// <summary>
    /// The push function
    /// </summary>
    public string? Func { get; init; }

    /// <summary>
    /// The push source field
    /// </summary>
    public string? Arg { get; init; }

    /// <summary>
    /// The authentication policy, normally row policy
    /// </summary>
    public PolicyItem[]? Auths { get; private init; }

    /// <summary>
    /// Row filter policy
    /// </summary>
    public RowPolicyItem[]? RowAuths { get; private init; }

    /// <summary>
    /// The column access policy
    /// </summary>
    public ColPolicyItem[]? ColAuths { get; private init; }

    /// <summary>
    /// The field storage topology, which defines how the field data is stored in the database.
    /// </summary>
    public FieldStorageTopology? Topology { get; set; }

    /// <summary>
    /// The given table name if specified, otherwise the table name will be generated by the system based on the app and field name
    /// </summary>
    public string? TableName { get; set; }
    
    /// <summary>
    /// The given attribute table name if specified, otherwise the attribute table name will be generated by the system based on the app and field name
    /// </summary>
    public string? AttrTableName { get; set; }
    
    /// <summary>
    /// Enable template feature
    /// </summary>
    public bool? Template { get; private init; }
    
    /// <summary>
    /// Enable clear data
    /// </summary>
    public bool? AllowClear { get; private init; }

    /// <summary>
    /// The field is using increase update, no full data push allowed
    /// </summary>
    public bool? IncrUpdate { get; private init; }

    /// <summary>
    /// The field is front-end only, no data storage
    /// </summary>
    public bool? Frontend { get; private init; }

    /// <summary>
    /// The field is disabled
    /// </summary>
    public bool? Disable { get; private init; }
    
    /// <summary>
    /// The field is readonly
    /// </summary>
    public bool? Readonly { get; private init; }

    /// <summary>
    /// The combine rule for scalar/enum type
    /// </summary>
    public DataCombineType? Combine { get; private init; }

    /// <summary>
    /// The combine rule for struct or struct-array type
    /// </summary>
    public DataCombine[]? Combines { get; private init; }

    /// <summary>
    /// The field filters
    /// </summary>
    public FieldFilter[]? Filters { get; private init; }
    
    /// <summary>
    /// The additional data
    /// </summary>
    public Dictionary<string, JsonElement>? Additional { get; private init; }

    #endregion

    #region States

    /// <summary>
    /// The application field node status
    /// </summary>
    public SchemaNodeStatus? Status { get; internal set; }

    /// <summary>
    /// Enable dynamic table
    /// </summary>
    public bool EnableDynamicTable => !(Frontend ?? false) && !(Disable ?? false);

    /// <summary>
    /// Has observers
    /// </summary>
    public bool HasObserver => _observers is { Count: > 0 };

    #endregion

    #region Relationship

    /// <summary>
    /// The application node
    /// </summary>
    public AppType Application { get; internal set; } = null!;
    
    /// <summary>
    /// The field type node
    /// </summary>
    public AnySchemaType? SchemaType { get; internal set; }

    /// <summary>
    /// The field function node
    /// </summary>
    public FunctionType? FuncNode { get; internal set; }

    /// <summary>
    /// The fields that subscribe the update of this field.
    /// </summary>
    public IReadOnlyList<AppFieldType>? Observers => _observers;
    
    /// <summary>
    ///  the observers in the same app
    /// </summary>
    List<AppFieldType>? _observers;

    /// <summary>
    /// The call arguments
    /// </summary>
    public AppFieldType? PushSource { get; internal set; }
    
    /// <summary>
    /// The push function schema
    /// </summary>
    public FunctionTypeSchema? PushFuncSchema { get; internal set; }
    
    /// <summary>
    /// The third-party push field info
    /// </summary>
    public DataPushThirdFieldInfo[]? ThirdPushFields { get; internal set; }
    
    /// <summary>
    /// The dynamic table schema
    /// </summary>
    public DynamicTableSchema? Schema { get; internal set; }
    
    /// <summary>
    /// The field is single value
    /// </summary>
    public bool Single => SchemaType is not ArrayType arr || arr.Primary == null || arr.Primary.Length == 0;

    #endregion
    
    #region Method
    
    /// <summary>
    /// Add observer
    /// </summary>
    public void AddObserver(AppFieldType observer)
    {
        _observers ??= [];
        if (!_observers.Contains(observer))
            _observers.Add(observer);
    }
    
    /// <summary>
    /// Gets the authentication policies with the scope
    /// </summary>
    public IEnumerable<PolicyItem> GetAuthPolicies(PolicyScope scope)
    {
        // Application policy first
        foreach (var i in Application.GetAuthPolicies(scope)) yield return i;

        // self policies
        if (Auths == null) yield break;
        foreach (var i in Auths.Where(p => p.Scope == scope))
            yield return i;
    }

    /// <summary>
    /// Gets the field authentication policies with the scope
    /// </summary>
    public IEnumerable<string> GetColPolicies(string fieldName)
    {
        ColPolicyItem? item = ColAuths?.FirstOrDefault(i => i.Name.Equals(fieldName, StringComparison.OrdinalIgnoreCase));
        if (item == null || item.Evaluators.Length == 0) yield break;
        foreach (var evaluator in item.Evaluators)
            yield return evaluator;
    }
    
    #endregion

    #region Conversions

    /// <summary>
    /// Gets the field node from entity
    /// </summary>
    public static implicit operator AppFieldType(AppFieldSchema entity)
    {
        return new AppFieldType
        {
            Name = entity.Name,
            Type = entity.Type,
            Seqno = entity.Seqno,
            Display = entity.Display,
            Desc = entity.Desc,
            Topology = entity.Topology,
            TableName = entity.TableName,
            AttrTableName = entity.AttrTableName,
            Template = entity.Template,
            AllowClear =  entity.AllowClear,
            Func = entity.Func,
            Arg = entity.Arg,
            Auths = entity.Auths,
            RowAuths = entity.RowAuths,
            ColAuths = entity.ColAuths,
            IncrUpdate = entity.IncrUpdate,
            Frontend = entity.Frontend,
            Disable = entity.Disable,
            Readonly = entity.Readonly,
            Combine = entity.Combine,
            Combines = entity.Combines,
            Filters = entity.Filters,
            Additional = entity.Additional,
        };
    }

    /// <summary>
    /// Convert the node to schema
    /// </summary>
    public static implicit operator AppFieldSchema(AppFieldType entity)
    {
        return new AppFieldSchema
        {
            App = entity.App,
            Name = entity.Name,
            Type = entity.Type,
            Seqno = entity.Seqno,
            Display = entity.Display,
            Desc = entity.Desc,
            Status = entity.Status,
            Topology = entity.Topology,
            TableName = entity.TableName,
            AttrTableName = entity.AttrTableName,
            Template = entity.Template,
            AllowClear = entity.AllowClear,
            Func = entity.Func,
            Arg = entity.Arg,
            Auths = entity.Auths,
            RowAuths = entity.RowAuths,
            ColAuths = entity.ColAuths,
            IncrUpdate = entity.IncrUpdate,
            Frontend = entity.Frontend,
            Disable = entity.Disable,
            Readonly = entity.Readonly,
            Combine = entity.Combine,
            Combines = entity.Combines,
            Filters = entity.Filters,
            Additional = entity.Additional,
        };
    }

    #endregion

    #region Dynamic table

    // Gets the data field dynamic table name
    public string DynamicTableName => !string.IsNullOrWhiteSpace(TableName)
        ? TableName 
        : $"{DYNAMIC_TABLE_PREFIX}_{Regex.Replace(App, @"\W+", "_")}_{Name}";
    
    /// <summary>
    /// Gets the attribute table name for the field, which is used to store the attribute data of the field, only for dynamic type
    /// </summary>
    public string AttributeTableName => Topology == FieldStorageTopology.AttributeBased
        ? (!string.IsNullOrWhiteSpace(AttrTableName) 
            ? AttrTableName 
            : !string.IsNullOrWhiteSpace(TableName) 
                ? $"{EAV_TABLE_PREFIX}_{TableName}" 
                : $"{EAV_TABLE_PREFIX}_{Regex.Replace(App, @"\W+", "_")}_{Name}")
        : string.Empty;

    // Generate the dynamic table schema
    public DynamicTableSchema GenDynamicTableSchema()
    {
        // Generate the fields
        AnySchemaType node = SchemaType!;
        List<DynamicTableField> fields = [];
        DataIndex[]? indexes = null;
        bool single = true;

        if (Frontend ?? false)
        {
            return new DynamicTableSchema
            {
                SchemaType = node,
                Single = true,
                Fields = fields,
            };
        }

        // context item isolation scope
        foreach ((string item, AnySchemaType type) in Application.GetScopeContextItems())
        {
            DataTypeInfo info = GetDataTypeInfo(type, new StructFieldConfig
            {
                UpLimit = type is ScalarType { IsString: true } ? ENTITY_PRIMARY_KEY_MAX_LEN.ToString() : null
            });
            fields.Add(new DynamicTableField
            {
                Name = item,
                Type = info.Type,
                MaxLength = info.MaxLength,
                SchemaType = type,
                Scope = true
            });
        }
        
        // value fields
        switch (node.Type)
        {
            case SchemaNode.Enum.SchemaType.Scalar:
            case SchemaNode.Enum.SchemaType.Enum:
            case SchemaNode.Enum.SchemaType.Json:
            {
                DataTypeInfo info = GetDataTypeInfo(node);
                fields.Add(new DynamicTableField
                {
                    Name = DYNAMIC_TABLE_VALUE_FIELD,
                    Type = info.Type,
                    MaxLength = info.MaxLength,
                    SchemaType = node
                });
                break;
            }
            case SchemaNode.Enum.SchemaType.Struct:
            {
                StructType structNode = (StructType)node;
                foreach (var sField in structNode.Fields.Where(p => !(p.DisplayOnly ?? false)))
                {
                    if (sField.SchemeType?.Type == SchemaNode.Enum.SchemaType.Struct) // Check if the sfield use a struct type
                    {
                        // As complex fields
                        StructType subStructNode = (StructType)sField.SchemeType;
                        foreach (var iField in subStructNode.Fields.Where(p => !(p.DisplayOnly ?? false)))
                        {
                            DataTypeInfo info = GetDataTypeInfo(iField.SchemeType!, iField);
                            fields.Add(new DynamicTableField
                            {
                                Name = $"{sField.Name}{COMPLEX_SEP}{iField.Name}",
                                Complex = new DataFieldComplexInfo
                                {
                                    Main = sField.Name,
                                    Field = iField.Name
                                },
                                Type = info.Type,
                                MaxLength = info.MaxLength,
                                SchemaType = iField.SchemeType!
                            });
                        }
                    }
                    else
                    {
                        DataTypeInfo info = GetDataTypeInfo(sField.SchemeType!, sField);
                        fields.Add(new DynamicTableField
                        {
                            Name = sField.Name,
                            Type = info.Type,
                            MaxLength = info.MaxLength,
                            SchemaType = sField.SchemeType!
                        });
                    }
                }
                break;
            }
            case SchemaNode.Enum.SchemaType.Array:
            {
                ArrayType arrayNode = (ArrayType)node;
                node = arrayNode.ElementSchemaType!; // Record the base node for array
                indexes = arrayNode.Indexes;
                if (node is StructType structNode && arrayNode.Primary is { Length: > 0 })
                {
                    single = false;
                    var enableAttrTable = Topology == FieldStorageTopology.AttributeBased;

                    // Add primary fields
                    foreach (string n in arrayNode.Primary)
                    {
                        var sField = structNode.Fields.First(p => p.Name == n);
                        DataTypeInfo info = GetDataTypeInfo(sField.SchemeType!, sField);
                        fields.Add(new DynamicTableField
                        {
                            Name = sField.Name,
                            Type = info.Type,
                            Primary = true,
                            MaxLength = info.MaxLength,
                            SchemaType = sField.SchemeType!
                        });
                    }
                    
                    // Add normal fields
                    foreach (var sField in structNode.Fields.Where(p => !arrayNode.Primary.Contains(p.Name) && p.DisplayOnly != true))
                    {                        
                        // Check if the s-field use a struct type
                        if (sField.SchemeType!.Type == SchemaNode.Enum.SchemaType.Struct)
                        {
                            // As complex fields
                            foreach (var ifield in ((StructType)sField.SchemeType).Fields.Where(p => !(p.DisplayOnly ?? false)))
                            {
                                DataTypeInfo info = GetDataTypeInfo(ifield.SchemeType!, ifield);
                                fields.Add(new DynamicTableField
                                {
                                    Name = $"{sField.Name}{COMPLEX_SEP}{ifield.Name}",
                                    Complex = new DataFieldComplexInfo
                                    {
                                        Main = sField.Name,
                                        Field = ifield.Name
                                    },
                                    Type = info.Type,
                                    MaxLength = info.MaxLength,
                                    SchemaType = ifield.SchemeType!
                                });
                            }
                        }
                        // Check if the field is a dynamic JSON field with attribute-based topology, which need to be stored in separated attribute table
                        else if (sField.SchemeType is JsonType && enableAttrTable)
                        {
                            AppRelationSchema? typeRelation = Application.Relations?.FirstOrDefault(r => r.Type == RelationType.Type && 
                                r.FieldNode == this && sField.Name.Equals(r.DataField, StringComparison.OrdinalIgnoreCase));
                            StructFieldRelation? fieldRelation = structNode.Relations?.FirstOrDefault(r => r.Type == RelationType.Type &&
                                r.Field.Equals(sField.Name, StringComparison.OrdinalIgnoreCase));
                            
                            DataTypeInfo info = GetDataTypeInfo(sField.SchemeType, sField);
                            fields.Add(new DynamicTableField
                            {
                                Name = sField.Name,
                                Type = info.Type,
                                MaxLength = info.MaxLength,
                                SchemaType = sField.SchemeType!,
                                RelationType = typeRelation,
                                StructRelation = fieldRelation
                            });
                        }
                        else
                        {
                            DataTypeInfo info = GetDataTypeInfo(sField.SchemeType, sField);
                            fields.Add(new DynamicTableField
                            {
                                Name = sField.Name,
                                Type = info.Type,
                                MaxLength = info.MaxLength,
                                SchemaType = sField.SchemeType!
                            });
                        }
                    }
                }
                else
                {
                    fields.Add(new DynamicTableField
                    {
                        Name = DYNAMIC_TABLE_VALUE_FIELD,
                        Type = DynamicTableFieldType.Json,
                        SchemaType = node
                    });
                }
                break;
            }
            default:
                throw new ArgumentOutOfRangeException();
        }
        return new DynamicTableSchema
        {
            AppFieldType = this,
            SchemaType = node,
            Single = single,
            Fields = fields,
            Indexes = indexes,
            IncrUpdate = IncrUpdate ?? false,
        };
    }

    // Get scalar type mapping info
    static DataTypeInfo GetDataTypeInfo(AnySchemaType node, StructFieldConfig? field = null)
    {
        if (node is ScalarType scalar)
        {
            // Get base scalar data type info
            DataTypeInfo info = JsonDataType;
            if (scalar.IsNumber)
            {
                decimal? upLimit = !string.IsNullOrEmpty(field?.UpLimit) && decimal.TryParse(field.UpLimit, out decimal u) ? u : scalar.UpLimit;
                decimal? lowLimit = !string.IsNullOrEmpty(field?.LowLimit) && decimal.TryParse(field.LowLimit, out decimal l) ? l : scalar.LowLimit;

                // Check Number value
                if (scalar.IsInt)
                {
                    // No Limit
                    if (!upLimit.HasValue || !lowLimit.HasValue)
                    {
                        info = new DataTypeInfo
                        {
                            Type = DynamicTableFieldType.BigInt
                        };
                    }
                    // Check Range
                    else if (lowLimit >= 0)
                    {
                        // Unsigned
                        decimal maxVal = upLimit.Value;
                        info = new DataTypeInfo
                        {
                            Type = maxVal switch
                            {
                                <= 0xffff => DynamicTableFieldType.USmallint,
                                <= 0xffffff => DynamicTableFieldType.UMediumint,
                                <= 0xffffffff => DynamicTableFieldType.UInt,
                                _ => DynamicTableFieldType.UBigInt
                            }
                        };
                    }
                    else
                    {
                        // Signed
                        decimal maxVal = Math.Max(Math.Abs(lowLimit.Value), Math.Abs(upLimit.Value));
                        info = new DataTypeInfo
                        {
                            Type = maxVal switch
                            {
                                <= 0x7fff => DynamicTableFieldType.Smallint,
                                <= 0x7fffff => DynamicTableFieldType.Mediumint,
                                <= 0x7fffffff => DynamicTableFieldType.Int,
                                _ => DynamicTableFieldType.BigInt
                            }
                        };
                    }
                }
                else if (scalar.IsSingle)
                {
                    info = new DataTypeInfo
                    {
                        Type = DynamicTableFieldType.Float
                    };
                }
                else
                {
                    info = new DataTypeInfo
                    {
                        Type = DynamicTableFieldType.Double
                    };
                }
            }
            else if (scalar.IsBool)
            {
                info = new DataTypeInfo
                {
                    Type = DynamicTableFieldType.Bool
                };
            }
            else if (scalar.IsString)
            {
                decimal? upLimit = !string.IsNullOrEmpty(field?.UpLimit) && decimal.TryParse(field.UpLimit, out decimal u) ? u : scalar.UpLimit;
                info = new DataTypeInfo
                {
                    Type = upLimit.HasValue ? upLimit.Value switch
                    {
                        <= 0xffff => DynamicTableFieldType.VarChar,
                        <= 0xffffff => DynamicTableFieldType.MediumText,
                        _ => DynamicTableFieldType.LongText
                    } : DynamicTableFieldType.LongText,
                    MaxLength = upLimit < 0xffff ? (int)upLimit.Value : null
                };
            }
            else if (scalar.IsDate)
            {
                info = new DataTypeInfo
                {
                    Type = DynamicTableFieldType.DateTime
                };
            }
            return info;
        }
        else if (node is EnumType @enum)
        {
            return new DataTypeInfo
            {
                Type = @enum.ValueType switch
                {
                    EnumValueType.String => DynamicTableFieldType.VarChar,
                    EnumValueType.Int => DynamicTableFieldType.BigInt,
                    EnumValueType.Flags => DynamicTableFieldType.UInt,
                    _ => throw new ArgumentOutOfRangeException()
                },
                MaxLength = @enum.ValueType == EnumValueType.String ? ENTITY_PRIMARY_KEY_MAX_LEN : null
            };
        }

        // Use Json for all others
        return JsonDataType;
    }

    static readonly DataTypeInfo JsonDataType = new()
    {
        Type = DynamicTableFieldType.Json
    };

    /// <summary>
    /// Validate field by DynamicTableSchema and return nullable
    /// </summary>
    public async Task<(bool isEmpty, AnySchemaNode? result, JsonNode? error)> ValidateDataAsync(SchemaContext context, JsonNode? token)
    {
        if (token.IsEmpty()) return (true, null, null);
        (AnySchemaNode? value, JsonNode? error) = await SchemaType!.ValidateValueAsync(context, token!);
        return (false, value, error);
    }

    #endregion
}

#region Dynamic Data Helpers

/// <summary>
/// The field data change info
/// </summary>
internal record FieldDataChangeData(TransactionChangeOperation Operation, AnySchemaNode? Value, AnySchemaNode? Origin);

// The transaction change data
internal class TransactionChangeData
{
    /// <summary>
    /// The change operations
    /// </summary>
    public Dictionary<AppFieldType, List<FieldDataChangeData>> Changes { get; } = new();
}

/// <summary>
/// The push levels
/// </summary>
internal class FieldDataPushLevel
{
    /// <summary>
    /// The fields to be updated
    /// </summary>
    public List<AppFieldType> Fields { get; } = new();

    /// <summary>
    /// The next level to be updated
    /// </summary>
    public FieldDataPushLevel? Next { get; set; }
}

/// <summary>
/// The push argument
/// </summary>
internal struct FieldDataPushArg
{
    /// <summary>
    /// The value
    /// </summary>
    public AnySchemaNode? Value { get; set; }

    /// <summary>
    /// The origin value
    /// </summary>
    public AnySchemaNode? Origin { get; set; }

    /// <summary>
    /// Whether is array data
    /// </summary>
    public bool IsArray => Type is ArrayType;

    /// <summary>
    /// The value type
    /// </summary>
    public AnySchemaType Type { get; set; }

    /// <summary>
    /// Whether is full data
    /// </summary>
    public bool IsFull { get; set; }

    /// <summary>
    /// Whether the data is changed
    /// </summary>
    public bool Changed { get; set; }
}

/// <summary>
/// The data type map info
/// </summary>
class DataTypeInfo
{
    /// <summary>
    /// The dynamic field type
    /// </summary>
    public DynamicTableFieldType Type { get; init; }

    /// <summary>
    /// The max length of the string type
    /// </summary>
    public int? MaxLength { get; init; }
}
#endregion