using SchemaNode.Attribute;
using SchemaNode.Enum;
using SchemaNode.Runtime;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Text.Json;
using System.Text.Json.Serialization;
using SchemaNode.Utility;
using static SchemaNode.Utility.Constant;
// ReSharper disable UnusedAutoPropertyAccessor.Global

namespace SchemaNode.Schema;

/// <summary>
/// The application field schema
/// </summary>
[SchemaApp]
public sealed class AppFieldSchema
{
    #region Info

    /// <summary>
    /// the application name
    /// </summary>
    [Index]
    [StringLength(ENTITY_PRIMARY_KEY_MAX_LEN)]
    public string App { get; set; } = string.Empty;

    /// <summary>
    /// The field name
    /// </summary>
    [Index]
    [StringLength(ENTITY_PRIMARY_KEY_MAX_LEN)]
    public string Name { get; set; } = default!;

    /// <summary>
    /// The seqno
    /// </summary>
    public int Seqno { get; set; }

    /// <summary>
    /// The field type
    /// </summary>
    [StringLength(ENTITY_PRIMARY_KEY_MAX_LEN)]
    public string Type { get; set; } = default!;
    
    /// <summary>
    /// The field display name
    /// </summary>
    public LocaleString? Display { get; set; }
    
    /// <summary>
    /// The field description
    /// </summary>
    public LocaleString? Desc { get; set; }

    #endregion

    #region Push Rule

    /// <summary>
    /// The calculate function
    /// </summary>
    [StringLength(ENTITY_PRIMARY_KEY_MAX_LEN)]
    public string? Func { get; set; }
    
    /// <summary>
    /// The input field
    /// </summary>
    public string? Arg { get; set; }

    #endregion

    #region Auth

    /// <summary>
    /// The authentication policy
    /// </summary>
    public PolicyItem[]? Auths { get; set; }

    /// <summary>
    /// Row filter policy
    /// </summary>
    public RowPolicyItem[]? RowAuths { get; set; }

    /// <summary>
    /// The column access policy
    /// </summary>
    public ColPolicyItem[]? ColAuths { get; set; }

    #endregion

    #region Storage

    /// <summary>
    /// The field storage topology, which defines how the field data is stored in the database.
    /// </summary>
    public FieldStorageTopology? Topology { get; set; }
    
    /// <summary>
    /// The given table name if specified, otherwise the table name will be generated by the system based on the app and field name
    /// </summary>
    public string? TableName { get; set; }
    
    /// <summary>
    /// The given attribute table name if specified, otherwise the attribute table name will be generated by the system based on the app and field name
    /// </summary>
    public string? AttrTableName { get; set; }

    #endregion

    #region View For other field

    /// <summary>
    /// The source app when the field is a view field
    /// </summary>
    public string? SourceApp { get; set; }

    /// <summary>
    /// The soure app field for the view field
    /// </summary>
    public string? SourceField { get; set; }

    #endregion

    #region Flags

    /// <summary>
    /// The field flags
    /// </summary>
    [JsonIgnore]
    public AppFieldFlags Flags { get; set; } = AppFieldFlags.None;

    /// <summary>
    /// The field is front-end only, no data storage
    /// </summary>
    [NotMapped]
    public bool? Frontend
    {
        get => Flags.Has(AppFieldFlags.Frontend);
        init => Flags = Flags.Turn(AppFieldFlags.Frontend, value);
    }

    /// <summary>
    /// The field is disabled
    /// </summary>
    [NotMapped]
    public bool? Disable
    {
        get => Flags.Has(AppFieldFlags.Disable);
        init => Flags = Flags.Turn(AppFieldFlags.Disable, value);
    }

    /// <summary>
    /// The field is readonly, data comes from other apps
    /// </summary>
    [NotMapped]
    public bool? Readonly
    {
        get => Flags.Has(AppFieldFlags.Readonly);
        init => Flags = Flags.Turn(AppFieldFlags.Readonly, value);
    }

    /// <summary>
    /// The field is using increase update, no full data push allowed
    /// </summary>
    [NotMapped]
    public bool? IncrUpdate
    {
        get => Flags.Has(AppFieldFlags.IncrUpdate);
        init => Flags = Flags.Turn(AppFieldFlags.IncrUpdate, value);
    }

    /// <summary>
    /// Enable the all clear option for the field
    /// </summary>
    [NotMapped]
    public bool? AllowClear
    {
        get => Flags.Has(AppFieldFlags.AllowClear);
        init => Flags = Flags.Turn(AppFieldFlags.AllowClear, value);
    }

    /// <summary>
    /// The dynamic table is maintained by system, means the schema don't create or update the table
    /// </summary>
    [NotMapped]
    public bool? SystemMaintain { get; set; }

    #endregion

    #region The data combine rules

    /// <summary>
    /// The combine rule for scalar/enum type
    /// </summary>
    public DataCombineType? Combine { get; set; }
    
    /// <summary>
    /// The combine rule for struct or struct-array type
    /// </summary>
    public DataCombine[]? Combines { get; set; }

    #endregion

    #region Filter

    /// <summary>
    /// The field filters
    /// </summary>
    public FieldFilter[]? Filters { get; set; }

    #endregion

    #region Status

    /// <summary>
    /// The additional data
    /// </summary>
    [JsonExtensionData]
    public Dictionary<string, JsonElement>? Additional { get; set; }

    /// <summary>
    /// The schema node status
    /// </summary>
    [NotMapped]
    public SchemaNodeStatus? Status { get; set; }

    #endregion

}

#region Supporting Types

/// <summary>
/// The app field flags for storage
/// </summary>
[Flags]
public enum AppFieldFlags
{
    None = 0,
    Frontend = 1 << 0,
    Disable = 1 << 1,
    Readonly = 1 << 2,
    IncrUpdate = 1 << 3,
    AllowClear = 1 << 4,
}

/// <summary>
/// The row policy item
/// </summary>
public sealed class RowPolicyItem
{
    /// <summary>
    /// The policy evaluatorm, if true will use the filter
    /// </summary>
    [Schema(NS_SYSTEM_SCHEMA_EVALUATOR_FUNC_TYPE)]
    public required string Evaluator { get; set; }

    /// <summary>
    /// The row filter function
    /// </summary>
    [Schema(NS_SYSTEM_SCHEMA_PREDICATE_FUNC_TYPE)]
    public string? Filter { get; set; }

    /// <summary>
    /// The function type of the evaluator
    /// </summary>
    [NotMapped]
    [JsonIgnore]
    public FunctionType? EvaluatorFunc { get; set; }

    /// <summary>
    /// The function type of the filter
    /// </summary>
    [NotMapped]
    [JsonIgnore]
    public FunctionType? FilterFunc { get; set; }
}

/// <summary>
/// The column policy item
/// </summary>
public sealed class ColPolicyItem
{
    /// <summary>
    /// The struct field name
    /// </summary>
    public required string Name { get; set; } = string.Empty;

    /// <summary>
    /// The column access evaluators
    /// </summary>
    public string[] Evaluators { get; set; } = [];

    /// <summary>
    /// The function type of the evaluator
    /// </summary>
    [NotMapped]
    [JsonIgnore]
    public FunctionType[] Functions { get; set; } = [];
}

/// <summary>
/// The field filter
/// </summary>
public sealed class FieldFilter
{
    /// <summary>
    /// The filter mode
    /// </summary>
    public FieldFilterMode Mode { get; set; } = FieldFilterMode.Exactly;

    /// <summary>
    /// The field name or filter function
    /// </summary>
    [StringLength(ENTITY_PRIMARY_KEY_MAX_LEN)]
    public string Filter { get; set; } = string.Empty;
    
    /// <summary>h
    /// The field filter resolve type, which defines how to resolve the filter when no match found
    /// </summary>
    public FieldFilterResolve? Resolve { get; set; }
}

#endregion