<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
	<TargetFramework>net10.0</TargetFramework>
	<LangVersion>14</LangVersion>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <NoWarn>$(NoWarn);SKEXP0001</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Npgsql" Version="10.0.1" />
    <PackageReference Include="Npgsql.DependencyInjection" Version="10.0.1" />
    <PackageReference Include="Pgvector" Version="0.3.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SchemaNode\SchemaNode.csproj" />
    <ProjectReference Include="..\SchemaNode.Ontology\SchemaNode.Ontology.csproj" />
  </ItemGroup>

</Project>
