using SchemaNode.Attribute;
using SchemaNode.Enum;
using SchemaNode.Runtime;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Text.Json;
using System.Text.Json.Serialization;
using static SchemaNode.Utility.Constant;
using static SchemaNode.Utility.AppConstant;
using SchemaKind = SchemaNode.Property.Record.SchemaKind;
using SchemaNode.Property.Core;
using SchemaNode.Scalar;
using SchemaNode.Struct;
using SchemaNode.Property.Common;
using SchemaNode.Function;
// ReSharper disable UnusedAutoPropertyAccessor.Global

namespace SchemaNode.Schema;

/// <summary>
/// The application field schema
/// </summary>
[Meta<SchemaType>($"{NS_SYSTEM_SCHEMA_APP_FIELD}.schema")]
[Meta<SchemaKind>(SCHEMA_KIND_APP_FIELD, SCHEMA_KIND_ORDER_APP_FIELD)]
[Meta<Append>(typeof(Display))]
public sealed class AppFieldSchema: ExtensibleSchema
{
    #region Info

    /// <summary>
    /// the application name
    /// </summary>
    [Meta<PrimaryIndex>(0)]
    [Meta<SchemaType>(typeof(AppType))]
    public string App { get; set; } = string.Empty;

    /// <summary>
    /// The field name
    /// </summary>
    [Meta<PrimaryIndex>(1)]
    [Meta<SchemaType>(typeof(Identifier))]
    public string Name { get; set; } = default!;

    /// <summary>
    /// The seqno
    /// </summary>
    public int Seqno { get; set; }

    /// <summary>
    /// The field type
    /// </summary>
    [Meta<SchemaType>(typeof(ValueType))]
    public string Type { get; set; } = default!;
    
    #endregion

    #region Push Rule

    /// <summary>
    /// The calculate function
    /// </summary>
    [Meta<SchemaType>(typeof(OneArgFuncType))]
    [Meta<Valid>(NS_SYSTEM_SCHEMA_REFLECT_FUNC_WITH_RETURN, NODE_SELF, $"${nameof(Type)}", true)]
    public string? Func { get; set; }

    /// <summary>
    /// The input field
    /// </summary>
    [Meta<SchemaType>(typeof(Identifier))]
    [Meta<EntrySource>($"{NS_SYSTEM_SCHEMA_REFLECT}.{nameof(SystemAppReflect.getappfields)}", $"${nameof(AppFieldSchema.App)}")]
    public string? Arg { get; set; }

    #endregion

    #region Auth

    /// <summary>
    /// The authentication policy
    /// </summary>
    public PolicyItem[]? Auths { get; set; }

    /// <summary>
    /// Row filter policy
    /// </summary>
    public RowPolicy[]? RowAuths { get; set; }

    /// <summary>
    /// The column access policy
    /// </summary>
    public ColPolicy[]? ColAuths { get; set; }

    #endregion

    #region Storage

    /// <summary>
    /// The field storage topology, which defines how the field data is stored in the database.
    /// </summary>
    public FieldStorageTopology? Topology { get; set; }
    
    /// <summary>
    /// The given table name if specified, otherwise the table name will be generated by the system based on the app and field name
    /// </summary>
    public string? TableName { get; set; }
    
    /// <summary>
    /// The given attribute table name if specified, otherwise the attribute table name will be generated by the system based on the app and field name
    /// </summary>
    public string? AttrTableName { get; set; }

    #endregion

    #region Flags

    /// <summary>
    /// The field flags
    /// </summary>
    [JsonIgnore]
    public AppFieldFlags Flags { get; set; } = AppFieldFlags.None;

    /// <summary>
    /// The field is front-end only, no data storage
    /// </summary>
    [NotMapped]
    public bool? Frontend
    {
        get => Flags.Has(AppFieldFlags.Frontend);
        init => Flags = Flags.Turn(AppFieldFlags.Frontend, value);
    }

    /// <summary>
    /// The field is disabled
    /// </summary>
    [NotMapped]
    public bool? Disable
    {
        get => Flags.Has(AppFieldFlags.Disable);
        init => Flags = Flags.Turn(AppFieldFlags.Disable, value);
    }

    /// <summary>
    /// The field is readonly, data comes from other apps
    /// </summary>
    [NotMapped]
    public bool? Readonly
    {
        get => Flags.Has(AppFieldFlags.Readonly);
        init => Flags = Flags.Turn(AppFieldFlags.Readonly, value);
    }

    /// <summary>
    /// The field is using increase update, no full data push allowed
    /// </summary>
    [NotMapped]
    public bool? IncrUpdate
    {
        get => Flags.Has(AppFieldFlags.IncrUpdate);
        init => Flags = Flags.Turn(AppFieldFlags.IncrUpdate, value);
    }

    /// <summary>
    /// Enable the all clear option for the field
    /// </summary>
    [NotMapped]
    public bool? AllowClear
    {
        get => Flags.Has(AppFieldFlags.AllowClear);
        init => Flags = Flags.Turn(AppFieldFlags.AllowClear, value);
    }

    /// <summary>
    /// The dynamic table is maintained by system, means the schema don't create or update the table
    /// </summary>
    [NotMapped]
    public bool? SystemMaintain { get; set; }

    #endregion

    #region The data combine rules

    /// <summary>
    /// The combine rule for scalar/enum type
    /// </summary>
    public DataCombineType? Combine { get; set; }
    
    /// <summary>
    /// The combine rule for struct or struct-array type
    /// </summary>
    public DataCombine[]? Combines { get; set; }

    #endregion

    #region Filter

    /// <summary>
    /// The field filters
    /// </summary>
    public FieldFilter[]? Filters { get; set; }

    #endregion

    #region Foreign & View Settings

    /// <summary>
    /// The foreign settings
    /// </summary>
    public Foreign[]? Foreigns { get; set; }

    /// <summary>
    /// The field is a view to source app field
    /// </summary>
    public FieldView? View { get; set; }

    #endregion

    #region Method

    /// <summary>
    /// Combine the custom schema
    /// </summary>
    internal void CombineCustomSchema(AppFieldSchema? otherSchema)
    {
        if (otherSchema == null) return;
        Display = Display != null ? Display.Concat(otherSchema.Display) : otherSchema.Display;
        Auths = Auths ?? otherSchema.Auths;
        RowAuths = RowAuths ?? otherSchema.RowAuths;
        ColAuths = ColAuths ?? otherSchema.ColAuths;
        Flags |= otherSchema.Flags;
        Combine = Combine ?? otherSchema.Combine;
        Combines = Combines ?? otherSchema.Combines;
        Filters = Filters ?? otherSchema.Filters;
        Foreigns = Foreigns ?? otherSchema.Foreigns;
        View = View ?? otherSchema.View;

        this.CombineExtensions(otherSchema);
    }

    #endregion
}

#region Supporting Types

/// <summary>
/// The app field flags for storage
/// </summary>
[Flags]
[Schema($"{NS_SYSTEM_SCHEMA_DEF_APP_FIELD}.flags")]
public enum AppFieldFlags
{
    None = 0,
    Frontend = 1 << 0,
    Disable = 1 << 1,
    Readonly = 1 << 2,
    IncrUpdate = 1 << 3,
    AllowClear = 1 << 4,
}

/// <summary>
/// The row policy item
/// </summary>
[Schema($"{NS_SYSTEM_SCHEMA_DEF_POLICY}.row")]
public sealed class RowPolicy
{
    /// <summary>
    /// The policy evaluatorm, if true will use the filter
    /// </summary>
    [Schema(NS_SYSTEM_SCHEMA_TYPE_RULE_EVALUATOR)]
    public required string Evaluator { get; set; }

    /// <summary>
    /// The row filter function
    /// </summary>
    [Schema(NS_SYSTEM_SCHEMA_TYPE_RULE_PREDICATE)]
    public string? Filter { get; set; }

    /// <summary>
    /// The function type of the evaluator
    /// </summary>
    [NotMapped]
    [JsonIgnore]
    public FunctionType? EvaluatorFunc { get; set; }

    /// <summary>
    /// The function type of the filter
    /// </summary>
    [NotMapped]
    [JsonIgnore]
    public FunctionType? FilterFunc { get; set; }
}

/// <summary>
/// The column policy item
/// </summary>
[Schema($"{NS_SYSTEM_SCHEMA_DEF_POLICY}.col")]
public sealed class ColPolicy
{
    /// <summary>
    /// The struct field name
    /// </summary>
    public required string Name { get; set; } = string.Empty;

    /// <summary>
    /// The column access evaluators
    /// </summary>
    public string[] Evaluators { get; set; } = [];

    /// <summary>
    /// The function type of the evaluator
    /// </summary>
    [NotMapped]
    [JsonIgnore]
    public FunctionType[] Functions { get; set; } = [];
}

/// <summary>
/// The field filter
/// </summary>
[Schema($"{NS_SYSTEM_SCHEMA_DEF_APP_FIELD}.filter")]
public sealed class FieldFilter
{
    /// <summary>
    /// The filter mode
    /// </summary>
    public FieldFilterMode Mode { get; set; } = FieldFilterMode.Exactly;

    /// <summary>
    /// The field name or filter function
    /// </summary>
    [StringLength(ENTITY_PRIMARY_KEY_MAX_LEN)]
    public string Filter { get; set; } = string.Empty;
    
    /// <summary>h
    /// The field filter resolve type, which defines how to resolve the filter when no contains found
    /// </summary>
    public FieldFilterResolve? Resolve { get; set; }
}

/// <summary>
/// The foreign settings
/// </summary>
[Schema($"{NS_SYSTEM_SCHEMA_DEF_APP_FIELD}.foreign")]
public sealed class Foreign
{
    /// <summary>
    /// The field refer to the other app target
    /// </summary>
    public string Field { get; set; } = string.Empty;

    /// <summary>
    /// The foreign app name
    /// </summary>
    [Schema(NS_SYSTEM_SCHEMA_DOMAIN_APP)]
    public string App { get; set; } = string.Empty;
}

[Schema($"{NS_SYSTEM_SCHEMA_DEF_APP_FIELD}.view")]
public sealed class FieldView
{
    /// <summary>
    /// The source application
    /// </summary>
    [Schema(NS_SYSTEM_SCHEMA_DOMAIN_APP)]
    public string App { get; set; } = string.Empty;

    /// <summary>
    /// The source field
    /// </summary>
    [Schema(NS_SYSTEM_SCHEMA_DOMAIN_FIELD)]
    public string Field { get; set; } = string.Empty;

    /// <summary>
    /// The target map field
    /// </summary>
    public string Map { get; set; } = string.Empty;

    [NotMapped]
    public AppType? AppType { get; set; }
}

#endregion